codecov:
  notify:
    require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: 50...100
  status:
    patch:
      default:
        target: 70%
    project:
      default:
        target: 85%

ignore:
  - src/pytask_markdown/_version.py
  - setup.py
