name: main

# Automatically cancel a previous run.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - '*'


jobs:

  run-tests-linux:

    name: Run tests for ${{ matrix.os }} on ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v3
      - name: create build environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
          environment-name: pytask-markdown
          cache-env: true
          extra-specs: |
            python=${{ matrix.python-version }}
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Install marp.
        shell: bash -l {0}
        run: npm install -g @marp-team/marp-cli@2.2.0
      - name: run pytest
        shell: bash -l {0}
        run: |
          micromamba activate pytask-markdown
          pytest --cov-report=xml --cov=./

      - name: Upload coverage report.
        if: runner.os == 'Linux' && matrix.python-version == '3.10'
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}


  run-tests-win-and-mac:

    name: Run tests for ${{ matrix.os }} on ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ['macos-latest', 'windows-latest']
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v3
      - name: create build environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
          environment-name: pytask-markdown
          cache-env: true
          extra-specs: |
            python=${{ matrix.python-version }}
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Install marp.
        shell: bash -l {0}
        run: npm install -g @marp-team/marp-cli@2.2.0
      - name: run pytest
        shell: bash -l {0}
        run: |
          micromamba activate pytask-markdown
          pytest -m "not slow and not jax"
